### ISSUE TITLE
Totem don't changed

### ISSUE THREAD

**Issue by N1zard** [LopyMine/My-Totem-Doll#2]
Either I'm doing something wrong or the mod doesn't change the totem. I enter my nickname in the command (/my-totem-doll refresh player N1zyyyy), the message about the change was, but the totem itself did not change. Another interesting point: In the settings shows totem in 2 hands at once, and if you take in-game totem, and go to the settings, in 1 hand will be steve, and in the other is my skin.

(v1.0.1+1.21)

![2024-07-25_12 54 08](https://github.com/user-attachments/assets/9a7e8624-e7b1-4612-aa13-325d62341c53)

**Comment by LopyMine** [comment]
You need to rename your totem in anvil to any player nickname, refresh commands literally only refresh already loaded skins

**Comment by LopyMine** [comment]
Resolved, I guess...

**Comment by N1zard** [comment]
Yes, I was just busy and didn’t check right away.  I also forgot to answer.  Thank you!
